version: "3"

services:
  back-end:
    build:
      context: omicsapp
    container_name: back-end
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"

  front-end:
    build:
      context: omicsfe
    container_name: front-end
    networks:
      - node-network
    tty: true
    environment:
      REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    ports:
      - "5173:5173"

networks:
  node-network:
    driver: bridge
